version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - gosec
    - misspell
    - revive
    - unconvert
    - unparam

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/robmilanesi/taskland
